name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
      - name: Build static site
        run: |
          mkdir -p static_site
          cp dashboard.html static_site/index.html
          
          # Debug information
          echo "Content of static_site directory:"
          ls -la static_site
          
          # Replace template variables with actual values
          sed -i 's/{{ last_updated }}/'"$(date +'%Y-%m-%d %H:%M:%S')"'/g' static_site/index.html
          sed -i 's/{{ now.year }}/'"$(date +'%Y')"'/g' static_site/index.html
          
          # Copy static assets if they exist
          if [ -d "static" ]; then
            echo "Copying static assets"
            mkdir -p static_site/static
            cp -r static/* static_site/static/
            echo "Static assets copied"
            ls -la static_site/static
          else
            echo "No static directory found"
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'static_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 